//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkzamenUtkin.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_UtkinEntities1 : DbContext
    {
        private static BD_UtkinEntities1 _context;

        public static BD_UtkinEntities1 GetContext()
        {
            if (_context == null)
                _context = new BD_UtkinEntities1();
            return _context;
        }
        public BD_UtkinEntities1()
            : base("name=BD_UtkinEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Tovar_Dekor> Tovar_Dekor { get; set; }
    }
}
