//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkzamenUtkin.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar_Dekor
    {
        public string T_Artikyl { get; set; }
        public string T_Naimenovanie { get; set; }
        public string T_EdIzmereniya { get; set; }
        public string T_Stoimost { get; set; }
        public string T_RazmerSkidki { get; set; }
        public string T_Proizvoditel { get; set; }
        public string T_Postavshik { get; set; }
        public string T_KategoriyaTovara { get; set; }
        public string T_Deystvouyasha { get; set; }
        public string T_KolichestvoNaSklade { get; set; }
        public string T_Opisanie { get; set; }
        public string T_Izobrazhenie { get; set; }
    }
}
