//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkzamenUtkin.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int U_Kod { get; set; }
        public string U_Familia { get; set; }
        public string U_Imya { get; set; }
        public string U_Otchestvo { get; set; }
        public string U_Login { get; set; }
        public string U_Parol { get; set; }
        public string U_Roli { get; set; }
    }
}
